name = "RBFCloud"
uuid = "3bc94118-ce41-4b40-8010-11eb3745f95c"
authors = ["Emily de Jong <edejong@caltech.edu>"]
version = "0.1.0"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
NonNegLeastSquares = "b7351bd1-99d9-5c5d-8786-f205a815c4d7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
